version: '3'

services:
  node:
    image: linux/node
    build: 
      context: dockerfile
      dockerfile: note.Dockerfile
    stdin_open: true
    
  ubuntu:
    image: linux/ubuntu
    build: 
      context: dockerfile
      dockerfile: ubuntu.Dockerfile
    stdin_open: true

networks:
  default:
    name: network
    ipam:
      config:
        - subnet: 192.168.40.0/24
        - gateway: 192.168.40.1