version: '3'

services:
  node:
    image: linux/node
    build: 
      context: dockerfile
      dockerfile: note.Dockerfile
    stdin_open: true
    
  ubuntu:
    image: linux/ubuntu
    build: 
      context: dockerfile
      dockerfile: ubuntu.Dockerfile
    stdin_open: true
    networks:
      - vlan

networks:
  vlan:
    name: vlan
    driver: macvlan
    driver_opts:
      parent: en0
    ipam:
      config:
        - subnet: 192.168.144.0/24
          gateway: 192.168.144.254
          ip_range: 192.168.144.1/30