version: '3'

services:
  node:
    image: linux/node
    build: 
      context: node
      dockerfile: Dockerfile
    stdin_open: true
  ubuntu:
    build: 
      context: ubuntu
      dockerfile: Dockerfile
    stdin_open: true