version: '3'

services:
  # Node
  node:
    image: linux/node
    build: 
      context: dockerfile
      dockerfile: note.Dockerfile
    stdin_open: true
    restart: always
    networks:
      - wlan
  # Ubuntu
  ubuntu:
    image: linux/ubuntu
    build: 
      context: dockerfile
      dockerfile: ubuntu.Dockerfile
    stdin_open: true
    restart: always
    networks:
      - wlan

networks:
  wlan:
    name: ipvlan
    driver_opts:
      parent: wlp3s0
    ipam:
      driver: default
      config:
        - subnet: 192.168.40.0/24
          gateway: 192.168.40.1